'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.26
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.26.
'
Namespace localhost3
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="EmployeesServiceCompatibleSoap", [Namespace]:="http://www.apress.com/ProASP.NET/")>  _
    Partial Public Class EmployeesServiceCompatible
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetEmployeeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetCustomEmployeeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Settings.Default.ConsoleClient_localhost3_EmployeesServiceCompatible
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetEmployeeCompleted As GetEmployeeCompletedEventHandler
        
        '''<remarks/>
        Public Event GetCustomEmployeeCompleted As GetCustomEmployeeCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.apress.com/ProASP.NET/GetEmployee", RequestNamespace:="http://www.apress.com/ProASP.NET/", ResponseElementName:="EmployeeList", ResponseNamespace:="http://www.apress.com/ProASP.NET/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetEmployee() As Employee()
            Dim results() As Object = Me.Invoke("GetEmployee", New Object(-1) {})
            Return CType(results(0),Employee())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetEmployeeAsync()
            Me.GetEmployeeAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetEmployeeAsync(ByVal userState As Object)
            If (Me.GetEmployeeOperationCompleted Is Nothing) Then
                Me.GetEmployeeOperationCompleted = AddressOf Me.OnGetEmployeeOperationCompleted
            End If
            Me.InvokeAsync("GetEmployee", New Object(-1) {}, Me.GetEmployeeOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetEmployeeOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetEmployeeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetEmployeeCompleted(Me, New GetEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.apress.com/ProASP.NET/GetCustomEmployee", RequestNamespace:="http://www.apress.com/ProASP.NET/", ResponseNamespace:="http://www.apress.com/ProASP.NET/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetCustomEmployee() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetCustomEmployee", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetCustomEmployeeAsync()
            Me.GetCustomEmployeeAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetCustomEmployeeAsync(ByVal userState As Object)
            If (Me.GetCustomEmployeeOperationCompleted Is Nothing) Then
                Me.GetCustomEmployeeOperationCompleted = AddressOf Me.OnGetCustomEmployeeOperationCompleted
            End If
            Me.InvokeAsync("GetCustomEmployee", New Object(-1) {}, Me.GetCustomEmployeeOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetCustomEmployeeOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetCustomEmployeeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetCustomEmployeeCompleted(Me, New GetCustomEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.26"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.apress.com/ProASP.NET/")>  _
    Partial Public Class Employee
        
        Private employeeIDField As Integer
        
        Private firstNameField As String
        
        Private lastNameField As String
        
        Private titleOfCourtesyField As String
        
        '''<remarks/>
        Public Property EmployeeID() As Integer
            Get
                Return Me.employeeIDField
            End Get
            Set
                Me.employeeIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FirstName() As String
            Get
                Return Me.firstNameField
            End Get
            Set
                Me.firstNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LastName() As String
            Get
                Return Me.lastNameField
            End Get
            Set
                Me.lastNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TitleOfCourtesy() As String
            Get
                Return Me.titleOfCourtesyField
            End Get
            Set
                Me.titleOfCourtesyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")>  _
    Public Delegate Sub GetEmployeeCompletedEventHandler(ByVal sender As Object, ByVal e As GetEmployeeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetEmployeeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Employee()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Employee())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")>  _
    Public Delegate Sub GetCustomEmployeeCompletedEventHandler(ByVal sender As Object, ByVal e As GetCustomEmployeeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetCustomEmployeeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
End Namespace
