'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.26
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.26.
'
Namespace localhost
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Employees ServiceSoap", [Namespace]:="http://www.apress.com/ProASP.NET/")>  _
    Partial Public Class EmployeesService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetEmployeesLoggedOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetEmployeesSlowOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetEmployeesWseSecuredOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Settings.Default.WindowsClient_localhost_Employees_x0020_Service
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetEmployeesLoggedCompleted As GetEmployeesLoggedCompletedEventHandler
        
        '''<remarks/>
        Public Event GetEmployeesSlowCompleted As GetEmployeesSlowCompletedEventHandler
        
        '''<remarks/>
        Public Event GetEmployeesWseSecuredCompleted As GetEmployeesWseSecuredCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.apress.com/ProASP.NET/GetEmployeesLogged", RequestNamespace:="http://www.apress.com/ProASP.NET/", ResponseNamespace:="http://www.apress.com/ProASP.NET/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetEmployeesLogged() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetEmployeesLogged", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetEmployeesLoggedAsync()
            Me.GetEmployeesLoggedAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetEmployeesLoggedAsync(ByVal userState As Object)
            If (Me.GetEmployeesLoggedOperationCompleted Is Nothing) Then
                Me.GetEmployeesLoggedOperationCompleted = AddressOf Me.OnGetEmployeesLoggedOperationCompleted
            End If
            Me.InvokeAsync("GetEmployeesLogged", New Object(-1) {}, Me.GetEmployeesLoggedOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetEmployeesLoggedOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetEmployeesLoggedCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetEmployeesLoggedCompleted(Me, New GetEmployeesLoggedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.apress.com/ProASP.NET/GetEmployeesSlow", RequestNamespace:="http://www.apress.com/ProASP.NET/", ResponseNamespace:="http://www.apress.com/ProASP.NET/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetEmployeesSlow() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetEmployeesSlow", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetEmployeesSlowAsync()
            Me.GetEmployeesSlowAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetEmployeesSlowAsync(ByVal userState As Object)
            If (Me.GetEmployeesSlowOperationCompleted Is Nothing) Then
                Me.GetEmployeesSlowOperationCompleted = AddressOf Me.OnGetEmployeesSlowOperationCompleted
            End If
            Me.InvokeAsync("GetEmployeesSlow", New Object(-1) {}, Me.GetEmployeesSlowOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetEmployeesSlowOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetEmployeesSlowCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetEmployeesSlowCompleted(Me, New GetEmployeesSlowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.apress.com/ProASP.NET/GetEmployeesWseSecured", RequestNamespace:="http://www.apress.com/ProASP.NET/", ResponseNamespace:="http://www.apress.com/ProASP.NET/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetEmployeesWseSecured() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetEmployeesWseSecured", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetEmployeesWseSecuredAsync()
            Me.GetEmployeesWseSecuredAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetEmployeesWseSecuredAsync(ByVal userState As Object)
            If (Me.GetEmployeesWseSecuredOperationCompleted Is Nothing) Then
                Me.GetEmployeesWseSecuredOperationCompleted = AddressOf Me.OnGetEmployeesWseSecuredOperationCompleted
            End If
            Me.InvokeAsync("GetEmployeesWseSecured", New Object(-1) {}, Me.GetEmployeesWseSecuredOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetEmployeesWseSecuredOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetEmployeesWseSecuredCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetEmployeesWseSecuredCompleted(Me, New GetEmployeesWseSecuredCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")>  _
    Public Delegate Sub GetEmployeesLoggedCompletedEventHandler(ByVal sender As Object, ByVal e As GetEmployeesLoggedCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetEmployeesLoggedCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")>  _
    Public Delegate Sub GetEmployeesSlowCompletedEventHandler(ByVal sender As Object, ByVal e As GetEmployeesSlowCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetEmployeesSlowCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")>  _
    Public Delegate Sub GetEmployeesWseSecuredCompletedEventHandler(ByVal sender As Object, ByVal e As GetEmployeesWseSecuredCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetEmployeesWseSecuredCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
End Namespace
