'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50215.44
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports FileDataComponent

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

' 
' This source code was auto-generated by wsdl, Version=2.0.50215.44.
' 


''' <remarks/>
<System.Diagnostics.DebuggerStepThroughAttribute(), System.ComponentModel.DesignerCategoryAttribute("code"), System.Web.Services.WebServiceBindingAttribute(Name:="FileServiceSoap", Namespace:="http://tempuri.org/")> _
Public partial Class FileService : Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

	Private DownloadFileOperationCompleted As System.Threading.SendOrPostCallback

	''' <remarks/>
	Public Sub New()
		Me.Url = "http://localhost/WebServices2/FileService.asmx"
	End Sub

	''' <remarks/>
	Public Event DownloadFileCompleted As DownloadFileCompletedEventHandler

	''' <remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownloadFile", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)> _
 Public Function DownloadFile(<System.Xml.Serialization.XmlElementAttribute(Namespace:="http://tempuri.org/")> ByVal serverFileName As String) As FileData
        Dim results As Object() = Me.Invoke("DownloadFile", New Object() {serverFileName})
        Return (CType(results(0), FileData))
    End Function

	''' <remarks/>
	Public Function BeginDownloadFile(ByVal serverFileName As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
		Return Me.BeginInvoke("DownloadFile", New Object() { serverFileName}, callback, asyncState)
	End Function

	''' <remarks/>
	Public Function EndDownloadFile(ByVal asyncResult As System.IAsyncResult) As FileData
		Dim results As Object() = Me.EndInvoke(asyncResult)
		Return (CType(results(0), FileData))
	End Function

	''' <remarks/>
	Public Sub DownloadFileAsync(ByVal serverFileName As String)
		Me.DownloadFileAsync(serverFileName, Nothing)
	End Sub

	''' <remarks/>
	Public Sub DownloadFileAsync(ByVal serverFileName As String, ByVal userState As Object)
		If (Me.DownloadFileOperationCompleted Is Nothing) Then
			Me.DownloadFileOperationCompleted = New System.Threading.SendOrPostCallback(AddressOf Me.OnDownloadFileOperationCompleted)
		End If
		Me.InvokeAsync("DownloadFile", New Object() { serverFileName}, Me.DownloadFileOperationCompleted, userState)
	End Sub

	Private Sub OnDownloadFileOperationCompleted(ByVal arg As Object)
		If (Not Me.DownloadFileCompletedEvent Is Nothing) Then
			Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = (CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs))
			RaiseEvent DownloadFileCompleted(Me, New DownloadFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
		End If
	End Sub

	''' <remarks/>
	Public Shadows Sub CancelAsync(ByVal userState As Object)
		MyBase.CancelAsync(userState)
	End Sub
End Class

''' <remarks/>
Public Delegate Sub DownloadFileCompletedEventHandler(ByVal sender As Object, ByVal e As DownloadFileCompletedEventArgs)

''' <remarks/>
Public partial Class DownloadFileCompletedEventArgs : Inherits System.ComponentModel.AsyncCompletedEventArgs

	Private results As Object()

	Friend Sub New(ByVal results As Object(), ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
		MyBase.New(exception, cancelled, userState)
		Me.results = results
	End Sub

	''' <remarks/>
	Public ReadOnly Property Result() As FileData
		Get
			Me.RaiseExceptionIfNecessary()
			Return (CType(Me.results(0), FileData))
		End Get
	End Property
End Class
