'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.26
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.26.
'
Namespace localhost
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="EmployeesServiceSoap", [Namespace]:="http://www.apress.com/ProASP.NET/Compat")>  _
    Partial Public Class EmployeesService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetEmployeesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetEmployeesCountErrorOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.My.MySettings.Default.WindowsClient_localhost_EmployeesService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetEmployeesCompleted As GetEmployeesCompletedEventHandler
        
        '''<remarks/>
        Public Event GetEmployeesCountErrorCompleted As GetEmployeesCountErrorCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.apress.com/ProASP.NET/Compat/GetEmployees", RequestNamespace:="http://www.apress.com/ProASP.NET/Compat", ResponseNamespace:="http://www.apress.com/ProASP.NET/Compat", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetEmployees() As Employee()
            Dim results() As Object = Me.Invoke("GetEmployees", New Object(-1) {})
            Return CType(results(0),Employee())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetEmployeesAsync()
            Me.GetEmployeesAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetEmployeesAsync(ByVal userState As Object)
            If (Me.GetEmployeesOperationCompleted Is Nothing) Then
                Me.GetEmployeesOperationCompleted = AddressOf Me.OnGetEmployeesOperationCompleted
            End If
            Me.InvokeAsync("GetEmployees", New Object(-1) {}, Me.GetEmployeesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetEmployeesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetEmployeesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetEmployeesCompleted(Me, New GetEmployeesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.apress.com/ProASP.NET/Compat/GetEmployeesCountError", RequestNamespace:="http://www.apress.com/ProASP.NET/Compat", ResponseNamespace:="http://www.apress.com/ProASP.NET/Compat", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetEmployeesCountError() As Integer
            Dim results() As Object = Me.Invoke("GetEmployeesCountError", New Object(-1) {})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetEmployeesCountErrorAsync()
            Me.GetEmployeesCountErrorAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetEmployeesCountErrorAsync(ByVal userState As Object)
            If (Me.GetEmployeesCountErrorOperationCompleted Is Nothing) Then
                Me.GetEmployeesCountErrorOperationCompleted = AddressOf Me.OnGetEmployeesCountErrorOperationCompleted
            End If
            Me.InvokeAsync("GetEmployeesCountError", New Object(-1) {}, Me.GetEmployeesCountErrorOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetEmployeesCountErrorOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetEmployeesCountErrorCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetEmployeesCountErrorCompleted(Me, New GetEmployeesCountErrorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.26"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.apress.com/ProASP.NET/")>  _
    Partial Public Class Employee
        
        Private employeeIDField As Integer
        
        Private firstNameField As String
        
        Private lastNameField As String
        
        Private titleOfCourtesyField As String
        
        '''<remarks/>
        Public Property EmployeeID() As Integer
            Get
                Return Me.employeeIDField
            End Get
            Set
                Me.employeeIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FirstName() As String
            Get
                Return Me.firstNameField
            End Get
            Set
                Me.firstNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LastName() As String
            Get
                Return Me.lastNameField
            End Get
            Set
                Me.lastNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TitleOfCourtesy() As String
            Get
                Return Me.titleOfCourtesyField
            End Get
            Set
                Me.titleOfCourtesyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")>  _
    Public Delegate Sub GetEmployeesCompletedEventHandler(ByVal sender As Object, ByVal e As GetEmployeesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetEmployeesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Employee()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Employee())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")>  _
    Public Delegate Sub GetEmployeesCountErrorCompletedEventHandler(ByVal sender As Object, ByVal e As GetEmployeesCountErrorCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetEmployeesCountErrorCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
End Namespace
